apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aerovigil

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: aerovigilai/wind-turbine-pg-bnn
    newTag: latest

commonLabels:
  app.kubernetes.io/name: aerovigil-pg-bnn
  app.kubernetes.io/managed-by: kustomize
