apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aerovigil-data
  namespace: aerovigil
  labels:
    app: aerovigil-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
