import 'dart:convert';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import '../services/api_service.dart';
class DataIngestionScreen extends StatefulWidget { const DataIngestionScreen({super.key,required this.api}); final ApiService api; @override State<DataIngestionScreen> createState()=>_DataIngestionScreenState(); }
class _DataIngestionScreenState extends State<DataIngestionScreen>{String text=''; Future<void> pick() async { final f=await FilePicker.platform.pickFiles(withData:true,type:FileType.custom,allowedExtensions:['csv']); if(f?.files.single.bytes!=null){final r=await widget.api.post('/api/hardware/ingest',{'source':'usb','csv_text':utf8.decode(f!.files.single.bytes!)});setState(()=>text=jsonEncode(r));}} @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Hardware intake')),body:Padding(padding:const EdgeInsets.all(16),child:Column(children:[FilledButton(onPressed:pick,child:const Text('Select USB / CSV file')),SelectableText(text)])));}
class ApiJsonScreen extends StatefulWidget { const ApiJsonScreen({super.key,required this.api,required this.title,required this.path,required this.method}); final ApiService api;final String title,path,method; @override State<ApiJsonScreen> createState()=>_ApiJsonScreenState(); }
class _ApiJsonScreenState extends State<ApiJsonScreen>{final input=TextEditingController(text:'{}');String out=''; Future<void> run()async{try{final r=widget.method=='GET'?await widget.api.get(widget.path):await widget.api.post(widget.path,jsonDecode(input.text));setState(()=>out=const JsonEncoder.withIndent('  ').convert(r));}catch(e){setState(()=>out='$e');}} @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(widget.title)),body:Padding(padding:const EdgeInsets.all(16),child:Column(children:[TextField(controller:input,maxLines:6),FilledButton(onPressed:run,child:const Text('Run')),Expanded(child:SingleChildScrollView(child:SelectableText(out)))])));}
class DigitalTwinScreen extends ApiJsonScreen { DigitalTwinScreen({super.key,required super.api}):super(title:'Digital twin',path:'/api/twin/simulate',method:'POST'); }
class FleetReportsScreen extends ApiJsonScreen { FleetReportsScreen({super.key,required super.api}):super(title:'Fleet reports',path:'/api/fleet/report',method:'GET'); }
class AeroZipTelemetryScreen extends ApiJsonScreen { AeroZipTelemetryScreen({super.key,required super.api}):super(title:'AeroZip telemetry',path:'/api/telemetry/compress',method:'POST'); }
class LowLevelInferenceScreen extends ApiJsonScreen { LowLevelInferenceScreen({super.key,required super.api}):super(title:'Low-level inference',path:'/api/model/predict',method:'POST'); }
