name: release-apps
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      platform:
        description: "Platform"
        type: choice
        required: true
        default: all
        options: [all, windows, macos, linux, android]
      tag:
        description: "Tag"
        type: string
        required: false
        default: ""
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
